apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: workprofile_db
  MYSQL_USER: flaskapp
  MYSQL_PASSWORD: flaskapp

hellp

