apiVersion: apps/v1
kind: Deployment
metadata:
  name: workprofile-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workprofile
  template:
    metadata:
      labels:
        app: workprofile
    spec:
      containers:
      - name: workprofile
        image: workprofile:2.0
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: workprofile-config
        - secretRef:
            name: mysql-secret
